var sourceList = [{
    "website": "http://lifehacker.com",
    "url": "http://feeds.gawker.com/lifehacker/vip",
    "type": "Tech",
    "id": 1000,
    "name": "Lifehacker",
    "thumbnail": "/img/favicon/1000.png",
    "full": true
}, {
    "website": "http://techcrunch.com",
    "url": "http://feeds.feedburner.com/Techcrunch",
    "type": "Tech",
    "id": 1001,
    "name": "TechCrunch",
    "thumbnail": "/img/favicon/1001.png",
    "full": true
}, {
	website: "http://feeds.feedburner.com/fakingnews",
	url: "http://feeds.feedburner.com/fakingnews",
	type: "Other",
	id: 124467,
	full: false,
	name: 'Faking News'
}, {
    "website": "http://www.theverge.com/",
    "url": "http://www.theverge.com/rss/full.xml",
    "type": "Tech",
    "id": 1002,
    "name": "The Verge",
    "thumbnail": "/img/favicon/1002.png",
    "full": true
}, {
    "website": "http://mashable.com/stories/?utm_campaign=Mash-Prod-RSS-Feedburner-All-Part…tm_cid=Mash-Prod-RSS-Feedburner-All-Partial&utm_medium=feed&utm_source=rss",
    "url": "http://feeds.mashable.com/Mashable",
    "type": "Tech",
    "id": 1003,
    "name": "Mashable",
    "thumbnail": "/img/favicon/1003.png",
    "full": true
}, {
    "website": "http://www.engadget.com",
    "url": "http://www.engadget.com/rss.xml",
    "type": "Tech",
    "id": 1004,
    "name": "Engadget",
    "thumbnail": "/img/favicon/1004.png",
    "full": true
}, {
    "website": "http://readwrite.com",
    "url": "http://www.readwriteweb.com/rss.xml",
    "type": "Tech",
    "id": 1005,
    "name": "ReadWrite",
    "thumbnail": "/img/favicon/1005.png",
    "full": true
}, {
    "website": "http://thenextweb.com",
    "url": "http://feeds2.feedburner.com/thenextweb",
    "type": "Tech",
    "id": 1006,
    "name": "The Next Web",
    "thumbnail": "/img/favicon/1006.png",
    "full": true
}, {
    "website": "http://www.digitaltrends.com",
    "url": "http://www.digitaltrends.com/feed/?key=f00edf6a58d2a8740e624dda919cab37",
    "type": "Tech",
    "id": 1008,
    "name": "Digital Trends",
    "thumbnail": "/img/favicon/1008.png",
    "full": true
}, {
    "website": "http://abcnews.go.com/",
    "url": "http://feeds.abcnews.com/abcnews/topstories",
    "type": "News",
    "id": 10016,
    "name": "ABC News",
    "thumbnail": "/img/favicon/10016.png",
    "full": true
}, {
    "website": "http://www.reuters.com",
    "url": "http://feeds.reuters.com/reuters/topNews?irpc=69",
    "type": "News",
    "id": 10018,
    "name": "Reuters",
    "thumbnail": "/img/favicon/10018.png",
    "full": true
}, {
    "website": "http://www.nytimes.com/pages/index.html?partner=rss&emc=rss",
    "url": "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "type": "News",
    "id": 10019,
    "name": "The New York Times",
    "thumbnail": "/img/favicon/10019.png",
    "full": true
}, {
    "website": "http://www.usatoday.com",
    "url": "http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
    "type": "News",
    "id": 10022,
    "name": "USA Today",
    "thumbnail": "/img/favicon/10022.png",
    "full": true
}, {
    "website": "http://www.theguardian.com/world/usa",
    "url": "http://www.guardian.co.uk/world/usa/rss",
    "type": "News",
    "id": 10024,
    "name": "The Guardian",
    "thumbnail": "/img/favicon/10024.png",
    "full": true
}, {
    "website": "http://blogs.hbr.org",
    "url": "http://feeds.harvardbusiness.org/harvardbusiness/",
    "type": "Business",
    "id": 10030,
    "name": "HBR.org",
    "thumbnail": "/img/favicon/10030.png",
    "full": true
}, {
    "website": "http://sethgodin.typepad.com/seths_blog/",
    "url": "http://sethgodin.typepad.com/seths_blog/atom.xml",
    "type": "Business",
    "id": 10031,
    "name": "Seth Godin",
    "thumbnail": "/img/favicon/10031.png",
    "full": true
}, {
    "website": "http://www.avc.com/a_vc/",
    "url": "http://feeds.feedburner.com/AVc",
    "type": "Business",
    "id": 10032,
    "name": "A VC",
    "thumbnail": "/img/favicon/10032.png",
    "full": true
}, {
    "website": "http://allthingsd.com",
    "url": "http://allthingsd.com/feed/",
    "type": "Business",
    "id": 10033,
    "name": "All Things Digital",
    "thumbnail": "/img/favicon/10033.png",
    "full": true
}, {
    "website": "http://venturebeat.com",
    "url": "http://feeds.feedburner.com/venturebeat",
    "type": "Business",
    "id": 10034,
    "name": "VentureBeat",
    "thumbnail": "/img/favicon/10034.png",
    "full": true
}, {
    "website": "http://www.calculatedriskblog.com/",
    "url": "http://www.calculatedriskblog.com/feeds/posts/default",
    "type": "Business",
    "id": 10035,
    "name": "Calculated Risk",
    "thumbnail": "/img/favicon/10035.png",
    "full": true
}, {
    "website": "http://kotaku.com",
    "url": "http://feeds.gawker.com/kotaku/vip",
    "type": "gaming",
    "id": 10043,
    "name": "Kotaku",
    "thumbnail": "/img/favicon/10043.png",
    "full": true
}, {
    "website": "http://pipes.yahoo.com/pipes/pipe.info?_id=3c853897b3e044f5abd763d061015c37",
    "url": "http://feeds.ign.com/ign/games-all",
    "type": "gaming",
    "id": 10045,
    "name": "IGN Video Games",
    "thumbnail": "/img/favicon/10045.png",
    "full": true
}, {
    "website": "http://www.flesheatingzipper.com",
    "url": "http://www.flesheatingzipper.com/feed/",
    "type": "gaming",
    "id": 10046,
    "name": "FleshEatingZipper",
    "thumbnail": "/img/favicon/10046.png",
    "full": true
}, {
    "website": "http://indiegames.com/",
    "url": "http://www.indiegames.com/blog/atom.xml",
    "type": "gaming",
    "id": 10048,
    "name": "IndieGames",
    "thumbnail": "/img/favicon/10048.png",
    "full": true
}, {
    "website": "http://www.joystiq.com",
    "url": "http://ps3fanboy.com/rss.xml",
    "type": "gaming",
    "id": 10049,
    "name": "Joystiq",
    "thumbnail": "/img/favicon/10049.png",
    "full": true
}, {
    "website": "http://arstechnica.com",
    "url": "http://feeds.arstechnica.com/arstechnica/gaming/",
    "type": "gaming",
    "id": 10050,
    "name": "Opposable Thumbs",
    "thumbnail": "/img/favicon/10050.png",
    "full": true
}, {
    "website": "http://design-milk.com",
    "url": "http://feeds.feedburner.com/design-milk",
    "type": "Design",
    "id": 10059,
    "name": "Design Milk",
    "thumbnail": "/img/favicon/10059.png",
    "full": true
}, {
    "website": "http://www.swiss-miss.com",
    "url": "http://www.swiss-miss.com/feed",
    "type": "Design",
    "id": 10060,
    "name": "Swiss Miss",
    "thumbnail": "/img/favicon/10060.png",
    "full": true
}, {
    "website": "http://www.fubiz.net",
    "url": "http://www.fubiz.net/en/feed/",
    "type": "Design",
    "id": 10061,
    "name": "Fubiz",
    "thumbnail": "/img/favicon/10061.png",
    "full": true
}, {
    "website": "http://www.coolhunting.com",
    "url": "http://www.coolhunting.com/atom.xml",
    "type": "Design",
    "id": 10062,
    "name": "Cool Hunting",
    "thumbnail": "/img/favicon/10062.png",
    "full": true
}, {
    "website": "http://www.yankodesign.com",
    "url": "http://www.yankodesign.com/feed/",
    "type": "Design",
    "id": 10063,
    "name": "Yanko Design",
    "thumbnail": "/img/favicon/10063.png",
    "full": true
}, {
    "website": "http://www.fastcodesign.com",
    "url": "http://www.fastcodesign.com/rss.xml",
    "type": "Design",
    "id": 10064,
    "name": "Co.Design",
    "thumbnail": "/img/favicon/10064.png",
    "full": true
}, {
    "website": "http://freshome.com",
    "url": "http://feeds.feedburner.com/FreshInspirationForYourHome",
    "type": "Design",
    "id": 10066,
    "name": "Fresh Home",
    "thumbnail": "/img/favicon/10066.png",
    "full": true
}, {
    "website": "http://mocoloco.com/",
    "url": "http://mocoloco.com/index.rdf",
    "type": "Design",
    "id": 10067,
    "name": "MoCoLoco",
    "thumbnail": "/img/favicon/10067.png",
    "full": true
}, {
    "website": "http://theimpossiblecool.tumblr.com/",
    "url": "http://theimpossiblecool.tumblr.com/rss",
    "type": "Photography",
    "id": 10079,
    "name": "The Impossible Cool",
    "thumbnail": "/img/favicon/10079.png",
    "full": true
}, {
    "website": "http://photography.nationalgeographic.com/photography/photo-of-the-day/",
    "url": "http://www.nationalgeographic.com/rss/photography/photo-of-the-day",
    "type": "Photography",
    "id": 10080,
    "name": "National Geographic",
    "thumbnail": "/img/favicon/10080.png",
    "full": true
}, {
    "website": "http://www.boston.com/bigpicture/",
    "url": "http://www.boston.com/bigpicture/index.xml",
    "type": "Photography",
    "id": 10081,
    "name": "The Big Picture",
    "thumbnail": "/img/favicon/10081.png",
    "full": true
}, {
    "website": "http://wvs.topleftpixel.com/",
    "url": "http://wvs.topleftpixel.com/index.rdf",
    "type": "Photography",
    "id": 10082,
    "name": "daily dose of imagery",
    "thumbnail": "/img/favicon/10082.png",
    "full": true
}, {
    "website": "http://500px.com/blog/rss.rss",
    "url": "http://500px.com/blog/rss",
    "type": "Photography",
    "id": 10084,
    "name": "500px / Blog",
    "thumbnail": "/img/favicon/10084.png",
    "full": true
}, {
    "website": "http://www.stylebubble.co.uk/style_bubble/",
    "url": "http://www.stylebubble.co.uk/style_bubble/atom.xml",
    "type": "fashion",
    "id": 10094,
    "name": "Style Bubble",
    "thumbnail": "/img/favicon/10094.png",
    "full": true
}, {
    "website": "http://www.theblondesalad.com",
    "url": "http://www.theblondesalad.com/feeds/posts/default",
    "type": "fashion",
    "id": 10095,
    "name": "The Blonde Salad",
    "thumbnail": "/img/favicon/10095.png",
    "full": true
}, {
    "website": "http://www.fashionsquad.com",
    "url": "http://www.fashionsquad.com/feed/",
    "type": "fashion",
    "id": 10096,
    "name": "Fashion Squad",
    "thumbnail": "/img/favicon/10096.png",
    "full": true
}, {
    "website": "http://www.bubbyandbean.com/",
    "url": "http://www.bubbyandbean.com/feeds/posts/default",
    "type": "fashion",
    "id": 10097,
    "name": "Bubby and Bean ::: Living Creatively",
    "thumbnail": "/img/favicon/10097.png",
    "full": true
}, {
    "website": "http://www.seaofshoes.com/sea_of_shoes/",
    "url": "http://seaofshoes.typepad.com/sea_of_shoes/atom.xml",
    "type": "fashion",
    "id": 10098,
    "name": "Sea of Shoes",
    "thumbnail": "/img/favicon/10098.png",
    "full": true
}, {
    "website": "http://smittenkitchen.com",
    "url": "http://feeds.feedburner.com/smittenkitchen",
    "type": "Cooking",
    "id": 100111,
    "name": "smitten kitchen",
    "thumbnail": "/img/favicon/100111.png",
    "full": true
}, {
    "website": "http://blog.foodnetwork.com/fn-dish",
    "url": "http://blog.foodnetwork.com/fn-dish/feed/",
    "type": "Cooking",
    "id": 100113,
    "name": "Food Network Blog",
    "thumbnail": "/img/favicon/100113.png",
    "full": true
}, {
    "website": "http://www.latartinegourmande.com",
    "url": "http://www.latartinegourmande.com/feed/",
    "type": "Cooking",
    "id": 100114,
    "name": "La Tartine Gourmande",
    "thumbnail": "/img/favicon/100114.png",
    "full": true
}, {
    "website": "http://joythebaker.com",
    "url": "http://www.joythebaker.com/blog/feed/",
    "type": "Cooking",
    "id": 100115,
    "name": "Joy the Baker",
    "thumbnail": "/img/favicon/100115.png",
    "full": true
}, {
    "website": "http://chocolateandzucchini.com/",
    "url": "http://chocolateandzucchini.com/index.rdf",
    "type": "Cooking",
    "id": 100116,
    "name": "Chocolate & Zucchini",
    "thumbnail": "/img/favicon/100116.png",
    "full": true
}, {
    "website": "http://food52.com/blog",
    "url": "http://feeds.feedburner.com/food52-TheAandMBlog",
    "type": "Cooking",
    "id": 100117,
    "name": "Food52",
    "thumbnail": "/img/favicon/100117.png",
    "full": true
}, {
    "website": "http://deadspin.com",
    "url": "http://feeds.gawker.com/deadspin/vip",
    "type": "Sport",
    "id": 100143,
    "name": "Deadspin",
    "thumbnail": "/img/favicon/100143.png",
    "full": true
}, {
    "website": "http://bleacherreport.com/",
    "url": "http://bleacherreport.com/articles/feed",
    "type": "Sport",
    "id": 100144,
    "name": "Bleacher Report",
    "thumbnail": "/img/favicon/100144.png",
    "full": true
}, {
    "website": "http://www.grantland.com",
    "url": "http://feeds.feedburner.com/Grantland",
    "type": "Sport",
    "id": 100147,
    "name": "Grantland: Home Page",
    "thumbnail": "/img/favicon/100147.png",
    "full": true
}, {
    "website": "http://snowboarding.transworld.net",
    "url": "http://snowboarding.transworld.net/feed/",
    "type": "Sport",
    "id": 100148,
    "name": "Transworld Snowboarding",
    "thumbnail": "/img/favicon/100148.png",
    "full": true
}, {
    "website": "http://www.bruinsnation.com/",
    "url": "http://www.bruinsnation.com/atom/",
    "type": "Sport",
    "id": 100149,
    "name": "Bruins Nation",
    "thumbnail": "/img/favicon/100149.png",
    "full": true
}, {
    "website": "http://snowboardmag.com",
    "url": "http://snowboardmag.com/feed",
    "type": "Sport",
    "id": 100150,
    "name": "Snowboard Magazine",
    "thumbnail": "/img/favicon/100150.png",
    "full": true
}, {
    "website": "http://www.empireonline.com/",
    "url": "http://www.empireonline.com/rss/rss.asp",
    "type": "cinema",
    "id": 100158,
    "name": "Empire News",
    "thumbnail": "/img/favicon/100158.png",
    "full": true
}, {
    "website": "http://mubi.com/notebook/posts",
    "url": "http://mubi.com/notebook/posts.atom",
    "type": "cinema",
    "id": 100160,
    "name": "The Daily Notebook",
    "thumbnail": "/img/favicon/100160.png",
    "full": true
}, {
    "website": "http://www.firstshowing.net",
    "url": "http://www.firstshowing.net/feed/?full",
    "type": "cinema",
    "id": 100161,
    "name": "FirstShowing.net",
    "thumbnail": "/img/favicon/100161.png",
    "full": true
}, {
    "website": "http://www.rogerebert.com",
    "url": "http://blogs.suntimes.com/ebert/atom.xml",
    "type": "cinema",
    "id": 100162,
    "name": "Roger Ebert's Journal",
    "thumbnail": "/img/favicon/100162.png",
    "full": true
}, {
    "website": "http://www.davidbordwell.net/blog",
    "url": "http://www.davidbordwell.net/blog/?feed=atom",
    "type": "cinema",
    "id": 100163,
    "name": "Observations on film art",
    "thumbnail": "/img/favicon/100163.png",
    "full": true
}];